# ================================================================
# LOG-TRANSFORMED SENSITIVITY ANALYSIS
# Predictive validation of Automated vs Manual cristae measurements
# ================================================================
#
# Purpose
# -------
# This script is a sensitivity analysis for the main predictive workflow.
# It evaluates whether the main predictive conclusion remains similar after
# reducing the influence of very large values and heteroscedasticity by using
# a log1p transformation.
#
# Scientific question
# -------------------
# Does the predictive relationship between Automated and Manual measurements
# remain robust when the calibration model is fitted on the log-transformed
# scale?
#
# Validation design
# -----------------
# Leave-one-subject-out cross-validation (LOSO-CV):
#
#   1. hold out all images from one biological subject;
#   2. fit the model using all remaining subjects;
#   3. predict the held-out subject using fixed effects only;
#   4. repeat until every subject has been held out once.
#
# This preserves the biological hierarchy and prevents subject-level leakage.
#
# Log-scale model
# ---------------
#   log1p(Manual_ij) =
#       beta_0 + beta_1 * log1p(Automated_ij) + u_i + epsilon_ij
#
# where:
#   i = biological subject
#   j = image
#   u_i = subject-specific random intercept
#
# Back-transformation
# -------------------
# Predictions are returned to the original measurement scale.
#
# A Duan smearing correction is estimated independently inside every training
# fold using population-level training residuals. This reduces retransformation
# bias when converting log-scale predictions back to the original scale.
#
# Primary endpoint
# ----------------
# manual_mean_per_mito predicted from auto_mean_per_mito
#
# Secondary endpoint
# ------------------
# manual_total predicted from auto_total
#
# Benchmarks
# ----------
# 1. Automated identity:
#      predicted Manual = Automated
#
# 2. Training subject mean:
#      mean of subject-specific Manual means among the training subjects
#
# Run from repository root
# ------------------------
#   Rscript scripts/R/cristae_log_sensitivity_analysis.R
#
# The required Prism_input.xlsx file is generated by:
#   Rscript scripts/R/prepare_prism_input.R
#
# IMPORTANT
# ---------
# This script is a sensitivity analysis only.
# The primary predictive analysis remains the original-scale LOSO model.
# The purpose of this script is to assess robustness of the primary conclusion
# to log1p transformation and retransformation of predictions.
#
# Main outputs
# ------------
# - out-of-sample LOSO predictions
# - MAE, RMSE, bias, pooled CV R2
# - subject-balanced MAE and RMSE
# - predictive Q2 versus both benchmarks
# - calibration intercept and slope
# - subject-cluster bootstrap 95% confidence intervals
# - diagnostic figures
#
# ================================================================


# ----------------------------------------------------------------
# STEP 0: Analysis settings
# ----------------------------------------------------------------

N_BOOTSTRAP <- 2000L
RANDOM_SEED <- 20260811L
SINGULAR_TOL <- 1e-5


# ----------------------------------------------------------------
# STEP 1: Check and load required packages
# ----------------------------------------------------------------

required_packages <- c(
  "readxl",
  "dplyr",
  "ggplot2",
  "lme4",
  "tibble",
  "writexl"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste0(
      "Missing required R packages: ",
      paste(missing_packages, collapse = ", "),
      "\nInstall them before running this script."
    ),
    call. = FALSE
  )
}

library(readxl)
library(dplyr)
library(ggplot2)
library(lme4)
library(tibble)
library(writexl)


# ----------------------------------------------------------------
# STEP 2: Define repository-relative input and output paths
# ----------------------------------------------------------------

INPUT_FILE <- file.path(
  "results",
  "derived",
  "Prism_input.xlsx"
)
INPUT_SHEET <- "compare_images"

OUTPUT_DIR <- file.path(
  "results",
  "derived",
  "log_sensitivity_prediction"
)

if (!file.exists(INPUT_FILE)) {
  stop(
    paste0(
      "Input file was not found:\n",
      INPUT_FILE,
      "\n\nRun first:\n",
      "Rscript scripts/R/prepare_prism_input.R"
    ),
    call. = FALSE
  )
}

if (!dir.exists(OUTPUT_DIR)) {
  dir.create(
    OUTPUT_DIR,
    recursive = TRUE
  )
}

cat("\nInput:\n", INPUT_FILE, "\n", sep = "")
cat("\nOutput directory:\n", OUTPUT_DIR, "\n", sep = "")


# ----------------------------------------------------------------
# STEP 3: Helper functions
# ----------------------------------------------------------------

announce_step <- function(number, title) {
  cat(
    "\n===== STEP ",
    number,
    ": ",
    title,
    " =====\n",
    sep = ""
  )
}


safe_numeric <- function(x) {
  suppressWarnings(as.numeric(x))
}


model_convergence_status <- function(model) {

  optimizer_code <- model@optinfo$conv$opt
  convergence_messages <- model@optinfo$conv$lme4$messages

  optimizer_ok <- is.null(optimizer_code) ||
    all(unlist(optimizer_code, use.names = FALSE) == 0)

  messages_ok <- is.null(convergence_messages) ||
    length(convergence_messages) == 0

  list(
    ok = isTRUE(optimizer_ok) && isTRUE(messages_ok),
    optimizer_code = if (is.null(optimizer_code)) {
      NA_character_
    } else {
      paste(
        as.character(
          unlist(
            optimizer_code,
            use.names = FALSE
          )
        ),
        collapse = "; "
      )
    },
    message = if (
      is.null(convergence_messages) ||
        length(convergence_messages) == 0
    ) {
      ""
    } else {
      paste(
        as.character(convergence_messages),
        collapse = " | "
      )
    }
  )
}


predictive_r2 <- function(observed, predicted) {

  valid <- is.finite(observed) & is.finite(predicted)
  observed <- observed[valid]
  predicted <- predicted[valid]

  if (length(observed) == 0) {
    return(NA_real_)
  }

  denominator <- sum(
    (observed - mean(observed))^2
  )

  if (!is.finite(denominator) || denominator <= 0) {
    return(NA_real_)
  }

  numerator <- sum(
    (observed - predicted)^2
  )

  1 - numerator / denominator
}


predictive_q2 <- function(
    observed,
    predicted_model,
    predicted_reference
) {

  valid <- is.finite(observed) &
    is.finite(predicted_model) &
    is.finite(predicted_reference)

  observed <- observed[valid]
  predicted_model <- predicted_model[valid]
  predicted_reference <- predicted_reference[valid]

  if (length(observed) == 0) {
    return(NA_real_)
  }

  model_sse <- sum(
    (observed - predicted_model)^2
  )

  reference_sse <- sum(
    (observed - predicted_reference)^2
  )

  if (!is.finite(reference_sse) || reference_sse <= 0) {
    return(NA_real_)
  }

  1 - model_sse / reference_sse
}


performance_metrics <- function(
    data,
    prediction_column,
    subject_column = "subject_id"
) {

  valid <- is.finite(data$observed) &
    is.finite(data[[prediction_column]])

  d <- data[
    valid,
    ,
    drop = FALSE
  ]

  if (nrow(d) == 0) {
    return(
      c(
        n_images = 0,
        MAE = NA_real_,
        RMSE = NA_real_,
        bias_pred_minus_obs = NA_real_,
        R2_CV_pooled = NA_real_,
        subject_balanced_MAE = NA_real_,
        subject_balanced_RMSE = NA_real_
      )
    )
  }

  errors <- d[[prediction_column]] - d$observed

  subject_ids <- unique(
    as.character(
      d[[subject_column]]
    )
  )

  subject_mae <- numeric(
    length(subject_ids)
  )

  subject_mse <- numeric(
    length(subject_ids)
  )

  for (i in seq_along(subject_ids)) {

    keep <- as.character(
      d[[subject_column]]
    ) == subject_ids[i]

    subject_errors <- (
      d[[prediction_column]][keep] -
        d$observed[keep]
    )

    subject_mae[i] <- mean(
      abs(subject_errors)
    )

    subject_mse[i] <- mean(
      subject_errors^2
    )
  }

  c(
    n_images = nrow(d),
    MAE = mean(
      abs(errors)
    ),
    RMSE = sqrt(
      mean(
        errors^2
      )
    ),
    bias_pred_minus_obs = mean(
      errors
    ),
    R2_CV_pooled = predictive_r2(
      d$observed,
      d[[prediction_column]]
    ),
    subject_balanced_MAE = mean(
      subject_mae
    ),
    subject_balanced_RMSE = sqrt(
      mean(
        subject_mse
      )
    )
  )
}


calibration_metrics <- function(
    observed,
    predicted
) {

  valid <- is.finite(observed) &
    is.finite(predicted)

  observed <- observed[valid]
  predicted <- predicted[valid]

  if (
    length(observed) < 3 ||
      length(unique(predicted)) < 2
  ) {
    return(
      c(
        calibration_intercept = NA_real_,
        calibration_slope = NA_real_
      )
    )
  }

  fit <- stats::lm(
    observed ~ predicted
  )

  b <- stats::coef(
    fit
  )

  c(
    calibration_intercept = unname(
      b["(Intercept)"]
    ),
    calibration_slope = unname(
      b["predicted"]
    )
  )
}


cluster_bootstrap_metrics <- function(
    data,
    prediction_column,
    n_bootstrap,
    seed
) {

  subjects <- unique(
    as.character(
      data$subject_id
    )
  )

  if (length(subjects) < 2) {
    stop(
      "Cluster bootstrap requires at least two biological subjects.",
      call. = FALSE
    )
  }

  set.seed(seed)

  one_bootstrap <- function() {

    sampled_subjects <- sample(
      subjects,
      length(subjects),
      replace = TRUE
    )

    parts <- vector(
      "list",
      length(sampled_subjects)
    )

    for (k in seq_along(sampled_subjects)) {

      current <- data[
        as.character(data$subject_id) ==
          sampled_subjects[k],
        ,
        drop = FALSE
      ]

      current$bootstrap_cluster <- paste0(
        sampled_subjects[k],
        "__copy_",
        k
      )

      parts[[k]] <- current
    }

    bootstrap_data <- dplyr::bind_rows(
      parts
    )

    perf <- performance_metrics(
      bootstrap_data,
      prediction_column,
      subject_column = "bootstrap_cluster"
    )

    cal <- calibration_metrics(
      bootstrap_data$observed,
      bootstrap_data[[prediction_column]]
    )

    c(
      perf,
      cal
    )
  }

  metric_names <- names(
    one_bootstrap()
  )

  bootstrap_matrix <- t(
    replicate(
      n_bootstrap,
      one_bootstrap()
    )
  )

  bootstrap_df <- as.data.frame(
    bootstrap_matrix
  )

  names(bootstrap_df) <- metric_names

  rows <- lapply(
    metric_names,
    function(metric_name) {

      values <- bootstrap_df[[metric_name]]
      values <- values[
        is.finite(values)
      ]

      if (length(values) == 0) {
        return(
          tibble::tibble(
            metric = metric_name,
            bootstrap_median = NA_real_,
            ci_95_lower = NA_real_,
            ci_95_upper = NA_real_,
            valid_bootstrap_replicates = 0L,
            n_bootstrap_requested = n_bootstrap
          )
        )
      }

      tibble::tibble(
        metric = metric_name,
        bootstrap_median = stats::median(
          values
        ),
        ci_95_lower = unname(
          stats::quantile(
            values,
            0.025,
            names = FALSE
          )
        ),
        ci_95_upper = unname(
          stats::quantile(
            values,
            0.975,
            names = FALSE
          )
        ),
        valid_bootstrap_replicates = length(
          values
        ),
        n_bootstrap_requested = n_bootstrap
      )
    }
  )

  dplyr::bind_rows(
    rows
  )
}


cluster_bootstrap_q2 <- function(
    data,
    model_prediction_column,
    reference_prediction_column,
    n_bootstrap,
    seed,
    metric_name
) {

  subjects <- unique(
    as.character(
      data$subject_id
    )
  )

  if (length(subjects) < 2) {
    stop(
      "Cluster bootstrap requires at least two biological subjects.",
      call. = FALSE
    )
  }

  set.seed(seed)

  bootstrap_values <- replicate(
    n_bootstrap,
    {

      sampled_subjects <- sample(
        subjects,
        length(subjects),
        replace = TRUE
      )

      parts <- vector(
        "list",
        length(sampled_subjects)
      )

      for (k in seq_along(sampled_subjects)) {

        current <- data[
          as.character(data$subject_id) ==
            sampled_subjects[k],
          ,
          drop = FALSE
        ]

        parts[[k]] <- current
      }

      bootstrap_data <- dplyr::bind_rows(
        parts
      )

      predictive_q2(
        observed = bootstrap_data$observed,
        predicted_model =
          bootstrap_data[[model_prediction_column]],
        predicted_reference =
          bootstrap_data[[reference_prediction_column]]
      )
    }
  )

  values <- bootstrap_values[
    is.finite(bootstrap_values)
  ]

  if (length(values) == 0) {
    return(
      tibble::tibble(
        metric = metric_name,
        bootstrap_median = NA_real_,
        ci_95_lower = NA_real_,
        ci_95_upper = NA_real_,
        valid_bootstrap_replicates = 0L,
        n_bootstrap_requested = n_bootstrap
      )
    )
  }

  tibble::tibble(
    metric = metric_name,
    bootstrap_median = stats::median(
      values
    ),
    ci_95_lower = unname(
      stats::quantile(
        values,
        0.025,
        names = FALSE
      )
    ),
    ci_95_upper = unname(
      stats::quantile(
        values,
        0.975,
        names = FALSE
      )
    ),
    valid_bootstrap_replicates = length(
      values
    ),
    n_bootstrap_requested = n_bootstrap
  )
}


# ----------------------------------------------------------------
# STEP 4: Read and validate the input worksheet
# ----------------------------------------------------------------

announce_step(
  4,
  "Read and validate input data"
)

raw <- readxl::read_excel(
  INPUT_FILE,
  sheet = INPUT_SHEET
)

required_columns <- c(
  "group",
  "image_id",
  "manual_n_mito",
  "manual_total",
  "manual_mean_per_mito",
  "auto_n_mito",
  "auto_total",
  "auto_mean_per_mito"
)

missing_columns <- setdiff(
  required_columns,
  names(raw)
)

if (length(missing_columns) > 0) {
  stop(
    paste0(
      "The selected workbook is missing required columns: ",
      paste(
        missing_columns,
        collapse = ", "
      )
    ),
    call. = FALSE
  )
}


# ----------------------------------------------------------------
# STEP 5: Derive biological subject identifiers
# ----------------------------------------------------------------

announce_step(
  5,
  "Derive biological subject identifiers"
)

group_character <- as.character(
  raw$group
)

image_character <- as.character(
  raw$image_id
)

if (anyNA(group_character)) {
  stop(
    "Missing values detected in group.",
    call. = FALSE
  )
}

if (anyNA(image_character)) {
  stop(
    "Missing values detected in image_id.",
    call. = FALSE
  )
}

valid_ctrl_group <- grepl(
  "^Ctrl",
  group_character
)

valid_hd_group <- grepl(
  "^P[0-9]+$",
  group_character
)

unexpected_groups <- sort(
  unique(
    group_character[
      is.na(group_character) |
        !(valid_ctrl_group | valid_hd_group)
    ]
  )
)

if (length(unexpected_groups) > 0) {
  stop(
    paste0(
      "Unexpected group label(s): ",
      paste(
        unexpected_groups,
        collapse = ", "
      )
    ),
    call. = FALSE
  )
}

invalid_control_ids <- sort(
  unique(
    image_character[
      valid_ctrl_group &
        (
          is.na(image_character) |
            !grepl(
              "^C[12]_",
              image_character
            )
        )
    ]
  )
)

if (length(invalid_control_ids) > 0) {
  stop(
    paste0(
      "Unexpected control image ID(s): ",
      paste(
        invalid_control_ids,
        collapse = ", "
      )
    ),
    call. = FALSE
  )
}

analysis_data <- raw |>
  dplyr::mutate(
    subject_id = dplyr::case_when(
      grepl("^C1_", image_id) ~ "C1",
      grepl("^C2_", image_id) ~ "C2",
      grepl("^P[0-9]+$", group) ~ as.character(group),
      TRUE ~ NA_character_
    ),
    disease_status = dplyr::case_when(
      grepl("^Ctrl", group) ~ "Ctrl",
      grepl("^P[0-9]+$", group) ~ "HD",
      TRUE ~ NA_character_
    ),
    subject_id = factor(
      subject_id
    ),
    disease_status = factor(
      disease_status,
      levels = c(
        "Ctrl",
        "HD"
      )
    )
  )

duplicate_keys <- analysis_data |>
  dplyr::count(
    group,
    image_id,
    name = "n_rows"
  ) |>
  dplyr::filter(
    n_rows > 1
  )

if (nrow(duplicate_keys) > 0) {
  stop(
    "Duplicate group + image_id combinations were detected.",
    call. = FALSE
  )
}

subject_counts <- analysis_data |>
  dplyr::count(
    disease_status,
    subject_id,
    name = "n_images"
  )

print(
  subject_counts
)


# ----------------------------------------------------------------
# STEP 6: Define sensitivity-analysis endpoints
# ----------------------------------------------------------------

announce_step(
  6,
  "Define predictive endpoints"
)

endpoint_definitions <- tibble::tibble(
  endpoint = c(
    "cristae_per_mito",
    "total_cristae_per_image"
  ),
  role = c(
    "Primary",
    "Secondary"
  ),
  manual_response = c(
    "manual_mean_per_mito",
    "manual_total"
  ),
  automated_predictor = c(
    "auto_mean_per_mito",
    "auto_total"
  )
)

print(
  endpoint_definitions
)


# ----------------------------------------------------------------
# STEP 7: Run LOSO log-transformed sensitivity models
# ----------------------------------------------------------------

announce_step(
  7,
  "Run LOSO log-transformed sensitivity models"
)

all_predictions <- list()
all_fold_models <- list()
full_model_diagnostics <- list()
full_model_status <- list()

for (endpoint_index in seq_len(nrow(endpoint_definitions))) {

  endpoint_id <- endpoint_definitions$endpoint[
    endpoint_index
  ]

  response_column <- endpoint_definitions$manual_response[
    endpoint_index
  ]

  predictor_column <- endpoint_definitions$automated_predictor[
    endpoint_index
  ]

  cat(
    "\nRunning endpoint: ",
    endpoint_id,
    "\n",
    sep = ""
  )

  endpoint_data <- analysis_data |>
    dplyr::transmute(
      group,
      image_id,
      subject_id,
      disease_status,
      observed = safe_numeric(
        .data[[response_column]]
      ),
      automated = safe_numeric(
        .data[[predictor_column]]
      )
    ) |>
    dplyr::filter(
      is.finite(observed),
      is.finite(automated)
    )

  if (
    any(endpoint_data$observed < 0) ||
      any(endpoint_data$automated < 0)
  ) {
    stop(
      paste0(
        "Endpoint ",
        endpoint_id,
        " contains negative values and cannot be analyzed with log1p."
      ),
      call. = FALSE
    )
  }

  endpoint_data <- endpoint_data |>
    dplyr::mutate(
      log_observed = log1p(
        observed
      ),
      log_automated = log1p(
        automated
      )
    )

  if (nrow(endpoint_data) < 3) {
    stop(
      paste0(
        "Endpoint '",
        endpoint_id,
        "' contains fewer than three paired images."
      ),
      call. = FALSE
    )
  }

  subjects <- sort(
    unique(
      as.character(
        endpoint_data$subject_id
      )
    )
  )

  if (length(subjects) < 3) {
    stop(
      paste0(
        "Endpoint '",
        endpoint_id,
        "' requires at least three biological subjects."
      ),
      call. = FALSE
    )
  }

  prediction_parts <- vector(
    "list",
    length(subjects)
  )

  fold_parts <- vector(
    "list",
    length(subjects)
  )

  for (fold_index in seq_along(subjects)) {

    held_out_subject <- subjects[
      fold_index
    ]

    train <- endpoint_data |>
      dplyr::filter(
        as.character(subject_id) !=
          held_out_subject
      ) |>
      dplyr::mutate(
        subject_id = factor(
          subject_id
        )
      )

    test <- endpoint_data |>
      dplyr::filter(
        as.character(subject_id) ==
          held_out_subject
      )

    if (dplyr::n_distinct(train$subject_id) < 2) {
      stop(
        paste0(
          "Too few training subjects in LOSO fold for ",
          held_out_subject,
          "."
        ),
        call. = FALSE
      )
    }

    if (length(unique(train$log_automated)) < 2) {
      stop(
        paste0(
          "Insufficient predictor variability in LOSO fold for ",
          held_out_subject,
          "."
        ),
        call. = FALSE
      )
    }

    fit <- tryCatch(
      lme4::lmer(
        log_observed ~
          log_automated +
          (1 | subject_id),
        data = train,
        REML = TRUE,
        control = lme4::lmerControl(
          optimizer = "bobyqa",
          optCtrl = list(
            maxfun = 100000
          )
        )
      ),
      error = function(e) {
        stop(
          paste0(
            "Log-scale mixed model failed in LOSO fold for subject ",
            held_out_subject,
            ". Original error: ",
            conditionMessage(e)
          ),
          call. = FALSE
        )
      }
    )

    convergence <- model_convergence_status(
      fit
    )

    singular_fit <- lme4::isSingular(
      fit,
      tol = SINGULAR_TOL
    )

    # Population-level log predictions for training data.
    # These are used to estimate the fold-specific Duan smearing factor.
    train_log_prediction_population <- as.numeric(
      stats::predict(
        fit,
        newdata = train,
        re.form = NA,
        allow.new.levels = TRUE
      )
    )

    population_log_residual <- (
      train$log_observed -
        train_log_prediction_population
    )

    smearing_factor <- mean(
      exp(
        population_log_residual
      ),
      na.rm = TRUE
    )

    if (!is.finite(smearing_factor) || smearing_factor <= 0) {
      stop(
        paste0(
          "Invalid Duan smearing factor in LOSO fold for subject ",
          held_out_subject,
          "."
        ),
        call. = FALSE
      )
    }

    # Predict the held-out subject using fixed effects only.
    predicted_log <- as.numeric(
      stats::predict(
        fit,
        newdata = test,
        re.form = NA,
        allow.new.levels = TRUE
      )
    )

    # Naive retransformation is retained only as a diagnostic.
    predicted_naive_backtransform <- expm1(
      predicted_log
    )

    # Main sensitivity prediction on the original scale.
    # log1p(Y) is predicted; therefore:
    #   Y + 1 = exp(predicted_log) * smearing_factor
    #   Y     = exp(predicted_log) * smearing_factor - 1
    predicted_log_sensitivity <- (
      exp(
        predicted_log
      ) *
        smearing_factor -
        1
    )

    # Baseline 1: Automated value without statistical calibration.
    predicted_identity <- test$automated

    # Baseline 2: equal-weight average of training-subject Manual means.
    training_subject_mean <- train |>
      dplyr::group_by(
        subject_id
      ) |>
      dplyr::summarise(
        subject_mean = mean(
          observed
        ),
        .groups = "drop"
      ) |>
      dplyr::summarise(
        reference_mean = mean(
          subject_mean
        )
      ) |>
      dplyr::pull(
        reference_mean
      )

    predicted_training_subject_mean <- rep(
      training_subject_mean,
      nrow(test)
    )

    prediction_parts[[fold_index]] <- test |>
      dplyr::mutate(
        endpoint = endpoint_id,
        fold = fold_index,
        held_out_subject = held_out_subject,
        smearing_factor = smearing_factor,
        predicted_log_scale = predicted_log,
        predicted_naive_backtransform =
          predicted_naive_backtransform,
        predicted_log_sensitivity =
          predicted_log_sensitivity,
        predicted_identity =
          predicted_identity,
        predicted_training_subject_mean =
          predicted_training_subject_mean,
        negative_backtransformed_prediction =
          predicted_log_sensitivity < 0,
        residual_log_sensitivity =
          predicted_log_sensitivity -
          observed
      )

    variance_table <- as.data.frame(
      lme4::VarCorr(
        fit
      )
    )

    fixed_effects <- lme4::fixef(
      fit
    )

    fold_parts[[fold_index]] <- tibble::tibble(
      endpoint = endpoint_id,
      fold = fold_index,
      held_out_subject = held_out_subject,
      n_training_subjects =
        dplyr::n_distinct(
          train$subject_id
        ),
      n_training_images =
        nrow(train),
      n_test_images =
        nrow(test),
      intercept_log_scale =
        unname(
          fixed_effects["(Intercept)"]
        ),
      slope_log_automated =
        unname(
          fixed_effects["log_automated"]
        ),
      smearing_factor =
        smearing_factor,
      subject_random_intercept_sd =
        variance_table$sdcor[
          variance_table$grp ==
            "subject_id"
        ][1],
      residual_sd =
        variance_table$sdcor[
          variance_table$grp ==
            "Residual"
        ][1],
      singular_fit =
        singular_fit,
      convergence_ok =
        convergence$ok,
      optimizer_code =
        convergence$optimizer_code,
      convergence_message =
        convergence$message
    )
  }

  endpoint_predictions <- dplyr::bind_rows(
    prediction_parts
  )

  endpoint_fold_models <- dplyr::bind_rows(
    fold_parts
  )

  all_predictions[[endpoint_id]] <-
    endpoint_predictions

  all_fold_models[[endpoint_id]] <-
    endpoint_fold_models

  # Full-data log model for diagnostic inspection only.
  full_data <- endpoint_data |>
    dplyr::mutate(
      subject_id = factor(
        subject_id
      )
    )

  full_fit <- lme4::lmer(
    log_observed ~
      log_automated +
      (1 | subject_id),
    data = full_data,
    REML = TRUE,
    control = lme4::lmerControl(
      optimizer = "bobyqa",
      optCtrl = list(
        maxfun = 100000
      )
    )
  )

  full_convergence <- model_convergence_status(
    full_fit
  )

  full_model_status[[endpoint_id]] <-
    tibble::tibble(
      endpoint = endpoint_id,
      singular_fit =
        lme4::isSingular(
          full_fit,
          tol = SINGULAR_TOL
        ),
      convergence_ok =
        full_convergence$ok,
      optimizer_code =
        full_convergence$optimizer_code,
      convergence_message =
        full_convergence$message
    )

  full_model_diagnostics[[endpoint_id]] <-
    full_data |>
    dplyr::mutate(
      endpoint = endpoint_id,
      fitted_log_scale =
        as.numeric(
          stats::fitted(
            full_fit
          )
        ),
      residual_log_scale =
        as.numeric(
          stats::residuals(
            full_fit
          )
        )
    )
}

predictions <- dplyr::bind_rows(
  all_predictions
)

fold_models <- dplyr::bind_rows(
  all_fold_models
)

full_status <- dplyr::bind_rows(
  full_model_status
)

diagnostics <- dplyr::bind_rows(
  full_model_diagnostics
)

if (any(fold_models$singular_fit)) {
  warning(
    paste0(
      "At least one LOSO log-scale model is singular. ",
      "Inspect LOSO_fold_models before publication."
    ),
    call. = FALSE
  )
}

if (any(!fold_models$convergence_ok)) {
  warning(
    paste0(
      "At least one LOSO log-scale model reported an optimizer/convergence issue. ",
      "Inspect LOSO_fold_models before publication."
    ),
    call. = FALSE
  )
}

if (any(full_status$singular_fit)) {
  warning(
    "At least one full-data log-scale model is singular.",
    call. = FALSE
  )
}

if (any(!full_status$convergence_ok)) {
  warning(
    "At least one full-data log-scale model reported an optimizer/convergence issue.",
    call. = FALSE
  )
}

if (any(predictions$negative_backtransformed_prediction, na.rm = TRUE)) {
  warning(
    paste0(
      "At least one Duan-corrected back-transformed prediction is negative. ",
      "Predictions were not truncated; inspect LOSO_predictions before interpretation."
    ),
    call. = FALSE
  )
}


# ----------------------------------------------------------------
# STEP 8: Calculate predictive performance on the original scale
# ----------------------------------------------------------------

announce_step(
  8,
  "Calculate out-of-sample predictive performance"
)

strategy_map <- c(
  log_sensitivity =
    "predicted_log_sensitivity",
  automated_identity =
    "predicted_identity",
  training_subject_mean =
    "predicted_training_subject_mean"
)

overall_parts <- list()
subject_parts <- list()
q2_parts <- list()

for (endpoint_id in endpoint_definitions$endpoint) {

  d <- predictions |>
    dplyr::filter(
      endpoint == endpoint_id
    )

  endpoint_overall <- list()
  endpoint_subject <- list()

  for (strategy_name in names(strategy_map)) {

    prediction_column <-
      strategy_map[[strategy_name]]

    perf <- performance_metrics(
      d,
      prediction_column,
      subject_column = "subject_id"
    )

    # Calibration is meaningful for actual measurement-based predictions.
    # It is intentionally not interpreted for the training-subject-mean
    # no-information baseline.
    if (
      strategy_name ==
        "training_subject_mean"
    ) {
      cal <- c(
        calibration_intercept =
          NA_real_,
        calibration_slope =
          NA_real_
      )
    } else {
      cal <- calibration_metrics(
        d$observed,
        d[[prediction_column]]
      )
    }

    endpoint_overall[[strategy_name]] <-
      tibble::tibble(
        endpoint = endpoint_id,
        strategy = strategy_name,
        metric = c(
          names(perf),
          names(cal)
        ),
        estimate = c(
          as.numeric(perf),
          as.numeric(cal)
        )
      )

    subjects <- sort(
      unique(
        as.character(
          d$subject_id
        )
      )
    )

    subject_rows <- lapply(
      subjects,
      function(subject_name) {

        sd <- d |>
          dplyr::filter(
            as.character(subject_id) ==
              subject_name
          )

        errors <- (
          sd[[prediction_column]] -
            sd$observed
        )

        tibble::tibble(
          endpoint = endpoint_id,
          strategy = strategy_name,
          subject_id = subject_name,
          disease_status =
            as.character(
              sd$disease_status[1]
            ),
          n_images =
            nrow(sd),
          MAE =
            mean(
              abs(errors)
            ),
          RMSE =
            sqrt(
              mean(
                errors^2
              )
            ),
          bias_pred_minus_obs =
            mean(
              errors
            )
        )
      }
    )

    endpoint_subject[[strategy_name]] <-
      dplyr::bind_rows(
        subject_rows
      )
  }

  overall_parts[[endpoint_id]] <-
    dplyr::bind_rows(
      endpoint_overall
    )

  subject_parts[[endpoint_id]] <-
    dplyr::bind_rows(
      endpoint_subject
    )

  q2_parts[[endpoint_id]] <-
    tibble::tibble(
      endpoint = endpoint_id,
      metric = c(
        "Q2_vs_automated_identity",
        "Q2_vs_training_subject_mean"
      ),
      estimate = c(
        predictive_q2(
          d$observed,
          d$predicted_log_sensitivity,
          d$predicted_identity
        ),
        predictive_q2(
          d$observed,
          d$predicted_log_sensitivity,
          d$predicted_training_subject_mean
        )
      )
    )
}

overall_performance <- dplyr::bind_rows(
  overall_parts
)

subject_performance <- dplyr::bind_rows(
  subject_parts
)

q2_summary <- dplyr::bind_rows(
  q2_parts
)

print(
  overall_performance
)

cat(
  "\nPredictive Q2:\n"
)

print(
  q2_summary
)


# ----------------------------------------------------------------
# STEP 9: Subject-cluster bootstrap 95% confidence intervals
# ----------------------------------------------------------------

announce_step(
  9,
  "Calculate subject-cluster bootstrap confidence intervals"
)

bootstrap_metric_parts <- list()
bootstrap_q2_parts <- list()

for (endpoint_index in seq_len(nrow(endpoint_definitions))) {

  endpoint_id <- endpoint_definitions$endpoint[
    endpoint_index
  ]

  d <- predictions |>
    dplyr::filter(
      endpoint == endpoint_id
    )

  current_metric_rows <- list()

  for (strategy_index in seq_along(strategy_map)) {

    strategy_name <- names(
      strategy_map
    )[strategy_index]

    prediction_column <-
      strategy_map[[strategy_name]]

    current_ci <-
      cluster_bootstrap_metrics(
        data = d,
        prediction_column =
          prediction_column,
        n_bootstrap =
          N_BOOTSTRAP,
        seed =
          RANDOM_SEED +
          endpoint_index * 1000L +
          strategy_index
      ) |>
      dplyr::mutate(
        endpoint =
          endpoint_id,
        strategy =
          strategy_name,
        .before = 1
      )

    # Calibration of the no-information baseline is not interpreted.
    if (
      strategy_name ==
        "training_subject_mean"
    ) {
      current_ci <- current_ci |>
        dplyr::mutate(
          bootstrap_median =
            ifelse(
              metric %in%
                c(
                  "calibration_intercept",
                  "calibration_slope"
                ),
              NA_real_,
              bootstrap_median
            ),
          ci_95_lower =
            ifelse(
              metric %in%
                c(
                  "calibration_intercept",
                  "calibration_slope"
                ),
              NA_real_,
              ci_95_lower
            ),
          ci_95_upper =
            ifelse(
              metric %in%
                c(
                  "calibration_intercept",
                  "calibration_slope"
                ),
              NA_real_,
              ci_95_upper
            )
        )
    }

    current_metric_rows[[strategy_name]] <-
      current_ci
  }

  bootstrap_metric_parts[[endpoint_id]] <-
    dplyr::bind_rows(
      current_metric_rows
    )

  q2_identity <- cluster_bootstrap_q2(
    data = d,
    model_prediction_column =
      "predicted_log_sensitivity",
    reference_prediction_column =
      "predicted_identity",
    n_bootstrap =
      N_BOOTSTRAP,
    seed =
      RANDOM_SEED +
      5000L +
      endpoint_index,
    metric_name =
      "Q2_vs_automated_identity"
  )

  q2_training_mean <- cluster_bootstrap_q2(
    data = d,
    model_prediction_column =
      "predicted_log_sensitivity",
    reference_prediction_column =
      "predicted_training_subject_mean",
    n_bootstrap =
      N_BOOTSTRAP,
    seed =
      RANDOM_SEED +
      6000L +
      endpoint_index,
    metric_name =
      "Q2_vs_training_subject_mean"
  )

  bootstrap_q2_parts[[endpoint_id]] <-
    dplyr::bind_rows(
      q2_identity,
      q2_training_mean
    ) |>
    dplyr::mutate(
      endpoint = endpoint_id,
      .before = 1
    )
}

bootstrap_95CI <- dplyr::bind_rows(
  bootstrap_metric_parts
)

q2_bootstrap_95CI <- dplyr::bind_rows(
  bootstrap_q2_parts
)


# ----------------------------------------------------------------
# STEP 10: Create diagnostic and predictive figures
# ----------------------------------------------------------------

announce_step(
  10,
  "Create figures"
)

for (endpoint_id in endpoint_definitions$endpoint) {

  endpoint_dir <- file.path(
    OUTPUT_DIR,
    endpoint_id
  )

  if (!dir.exists(endpoint_dir)) {
    dir.create(
      endpoint_dir,
      recursive = TRUE
    )
  }

  d <- predictions |>
    dplyr::filter(
      endpoint == endpoint_id
    )

  p_prediction <- ggplot(
    d,
    aes(
      x = observed,
      y = predicted_log_sensitivity,
      shape = disease_status
    )
  ) +
    geom_point(
      alpha = 0.8,
      size = 2.5
    ) +
    geom_abline(
      intercept = 0,
      slope = 1,
      linetype = "dashed",
      linewidth = 0.7
    ) +
    labs(
      title = paste0(
        "Log-sensitivity LOSO prediction: ",
        endpoint_id
      ),
      subtitle =
        "Each subject was predicted by a model that did not contain that subject",
      x =
        "Observed Manual measurement",
      y =
        "Out-of-sample predicted Manual measurement",
      shape =
        "Biological group"
    ) +
    theme_bw()

  ggsave(
    filename = file.path(
      endpoint_dir,
      "01_log_sensitivity_predicted_vs_observed.png"
    ),
    plot = p_prediction,
    width = 7.4,
    height = 5.6,
    units = "in",
    dpi = 300
  )

  subject_plot_data <- subject_performance |>
    dplyr::filter(
      endpoint == endpoint_id,
      strategy %in% c(
        "log_sensitivity",
        "automated_identity"
      )
    ) |>
    dplyr::mutate(
      strategy = factor(
        strategy,
        levels = c(
          "automated_identity",
          "log_sensitivity"
        ),
        labels = c(
          "Automated identity",
          "Log-sensitivity LMM"
        )
      )
    )

  p_subject <- ggplot(
    subject_plot_data,
    aes(
      x = subject_id,
      y = MAE,
      shape = strategy
    )
  ) +
    geom_point(
      size = 2.8,
      position = position_dodge(
        width = 0.4
      )
    ) +
    labs(
      title = paste0(
        "Subject-level prediction error: ",
        endpoint_id
      ),
      x =
        "Held-out biological subject",
      y =
        "Mean absolute error (MAE)",
      shape =
        "Prediction strategy"
    ) +
    theme_bw()

  ggsave(
    filename = file.path(
      endpoint_dir,
      "02_subject_level_MAE.png"
    ),
    plot = p_subject,
    width = 8.2,
    height = 5.2,
    units = "in",
    dpi = 300
  )

  diagnostic_data <- diagnostics |>
    dplyr::filter(
      endpoint == endpoint_id
    )

  p_residual <- ggplot(
    diagnostic_data,
    aes(
      x = fitted_log_scale,
      y = residual_log_scale
    )
  ) +
    geom_point(
      alpha = 0.75,
      size = 2
    ) +
    geom_hline(
      yintercept = 0,
      linetype = "dashed"
    ) +
    labs(
      title = paste0(
        "Log-scale residuals versus fitted: ",
        endpoint_id
      ),
      x =
        "Fitted value on log1p scale",
      y =
        "Residual on log1p scale"
    ) +
    theme_bw()

  ggsave(
    filename = file.path(
      endpoint_dir,
      "03_log_scale_residuals_vs_fitted.png"
    ),
    plot = p_residual,
    width = 7.2,
    height = 5.2,
    units = "in",
    dpi = 300
  )

  p_qq <- ggplot(
    diagnostic_data,
    aes(
      sample = residual_log_scale
    )
  ) +
    stat_qq(
      size = 2
    ) +
    stat_qq_line() +
    labs(
      title = paste0(
        "Log-scale residual Q-Q plot: ",
        endpoint_id
      ),
      x =
        "Theoretical quantiles",
      y =
        "Sample quantiles"
    ) +
    theme_bw()

  ggsave(
    filename = file.path(
      endpoint_dir,
      "04_log_scale_residual_QQ.png"
    ),
    plot = p_qq,
    width = 7.2,
    height = 5.2,
    units = "in",
    dpi = 300
  )
}


# ----------------------------------------------------------------
# STEP 11: Export results to Excel
# ----------------------------------------------------------------

announce_step(
  11,
  "Export results"
)

output_file <- file.path(
  OUTPUT_DIR,
  "log_sensitivity_prediction_results.xlsx"
)

writexl::write_xlsx(
  list(
    endpoint_definitions =
      endpoint_definitions,
    subject_counts =
      subject_counts,
    LOSO_predictions =
      predictions,
    LOSO_fold_models =
      fold_models,
    overall_performance =
      overall_performance,
    predictive_Q2 =
      q2_summary,
    subject_performance =
      subject_performance,
    bootstrap_95CI =
      bootstrap_95CI,
    Q2_bootstrap_95CI =
      q2_bootstrap_95CI,
    full_model_status =
      full_status
  ),
  path = output_file
)


# ----------------------------------------------------------------
# STEP 12: Save a text summary
# ----------------------------------------------------------------

announce_step(
  12,
  "Save text summary"
)

report_file <- file.path(
  OUTPUT_DIR,
  "log_sensitivity_report.txt"
)

sink(
  report_file
)

cat(
  "LOG-TRANSFORMED PREDICTIVE SENSITIVITY ANALYSIS\n"
)

cat(
  "================================================\n\n"
)

cat(
  "Input file:\n",
  INPUT_FILE,
  "\n\n",
  sep = ""
)

cat(
  "Model:\n",
  "log1p(Manual) ~ log1p(Automated) + (1 | subject_id)\n\n",
  sep = ""
)

cat(
  "Validation:\n",
  "Leave-one-subject-out cross-validation.\n",
  "Held-out subjects were predicted with fixed effects only.\n",
  "Predictions were retransformed with a fold-specific Duan smearing correction.\n\n",
  sep = ""
)

cat(
  "===== OVERALL PERFORMANCE =====\n\n"
)

print(
  overall_performance
)

cat(
  "\n===== PREDICTIVE Q2 =====\n\n"
)

print(
  q2_summary
)

cat(
  "\n===== SUBJECT PERFORMANCE =====\n\n"
)

print(
  subject_performance
)

cat(
  "\n===== LOSO MODEL STATUS =====\n\n"
)

print(
  fold_models
)

cat(
  "\n===== FULL MODEL STATUS =====\n\n"
)

print(
  full_status
)

cat(
  "\n===== BOOTSTRAP 95% CIs =====\n\n"
)

print(
  bootstrap_95CI
)

cat(
  "\n===== Q2 BOOTSTRAP 95% CIs =====\n\n"
)

print(
  q2_bootstrap_95CI
)

sink()


# ----------------------------------------------------------------
# STEP 13: Save R session information
# ----------------------------------------------------------------

sink(
  file.path(
    OUTPUT_DIR,
    "R_session_info.txt"
  )
)

print(
  sessionInfo()
)

sink()


# ----------------------------------------------------------------
# STEP 14: Final message
# ----------------------------------------------------------------

announce_step(
  14,
  "Analysis completed"
)

cat(
  "\nSensitivity analysis completed successfully.\n\n"
)

cat(
  "Main result file:\n",
  output_file,
  "\n\n",
  sep = ""
)

cat(
  "Figures and reports were saved to:\n",
  OUTPUT_DIR,
  "\n",
  sep = ""
)
